version: "3.1"
services:
  {{Name}}:
    image: zenoss/zing-{{Name}}:dev
    build: .
    ports:
      - "{{Port}}:{{Port}}"
    environment:
      {{Name | toUpper}}_HTTP_PORT: {{Port}}
      {{Name | toUpper}}_AUTH_KEY_FILE: /run/secrets/auth_key
      {{Name | toUpper}}_LOG_LEVEL: info
    secrets:
      - auth_key
secrets:
  auth_key:
    file: dev.secret
