version: "3.3"
services:
  {{Name}}:
    image: ${SERVICE_IMAGE}:${IMAGE_TAG:-dev}
    build: 
        context: .
        labels:
          zenoss.zing.commit-sha: ${COMMIT_SHA:-none}
          zenoss.zing.pull-request: ${CHANGE_ID:-none}
          zenoss.zing.branch_name: ${BRANCH_NAME:-none}
          zenoss.zing.build_number: ${BUILD_ID:-none}
          zenoss.zing.build_url: ${BUILD_URL:-none}
    ports:
      - "{{Port}}:{{Port}}"
    environment:
      {{Name | toUpper}}_LOG_LEVEL: info
      {{Name | toUpper}}_HTTP_PORT: {{Port}}
      {{Name | toUpper}}_AUTH_DISABLED: 1
      {{Name | toUpper}}_AUTH_KEY_FILE: /run/secrets/auth_key
      {{Name | toUpper}}_TRACING_ENABLED: 0
    secrets:
      - auth_key
secrets:
  auth_key:
    file: dev.secret
