#
# This compose file is intended for integration testing
#
version: "3.3"
services:
  # bigtable:
  #   image: zenoss/gcloud-emulator:bigtable
  #   ports:
  #     - "8086"
  # pubsub:
  #   image: zenoss/gcloud-emulator:pubsub
  #   ports:
  #     - "8085"
  test:
    image: zenoss/zenkit-build:${ZENKIT_BUILD_VERSION}
    # depends_on:
    #   - bigtable
    #   - pubsub
    # environment:
    #   BIGTABLE_EMULATOR_HOST: "bigtable:8086"
    #   PUBSUB_EMULATOR_HOST: "pubsub:8085"