[[constraint]]
  version = "=4.0.0"
  name = "github.com/zenoss/zenkit"

[[constraint]]
  version = "=1.3.0"
  name = "github.com/zenoss/zing-proto"

[prune]
  go-tests = true
  unused-packages = true
