apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{Name}}"
  labels:
    app: "{{Name}}"
    project: "{{Name}}"
spec:
  minReplicas: 2
  maxReplicas: 16
  metrics:
    - type: ContainerResource
      containerResource:
        container: "{{Name}}"
        name: cpu
        target:
          type: AverageValue
          averageValue: 300
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{Name}}"
