apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - hpa.yaml
  - service.yaml
  - pdb.yaml
# - virtualservice.yaml // Uncomment this if you're exposing a public API.
