apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "{{Name}}"
  labels:
    app: "{{Name}}"
    project: "{{Name}}"
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: "{{Name}}"
