apiVersion: v1
kind: Service
metadata:
  name: {{Name}}
  labels:
    app: {{Name}}
    project: {{Name}}
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: grpc
  selector:
    app: {{Name}}
  type: ClusterIP
