#! groovy

MAKE='make -f ci/Makefile'

node('docker') {

    currentBuild.displayName = "PR #${env.ghprbPullId}@${env.NODE_NAME}"
    configFileProvider([
        configFile(fileId: 'global', variable: 'GLOBAL'),
    ]) {
        global = load env.GLOBAL
    }

    stage('Checkout') {
        checkout scm
    }

    withEnv([
        "COMMIT_SHA=${env.ghprbActualCommit}",
        "IMAGE_TAG=${env.ghprbActualCommit.substring(0,8)}",
        "PROJECT_NAME={{Name}}-${env.BUILD_NUMBER}",
        "ROOTDIR=${global.HOST_WORKSPACE}"]) {
        try {
            stage('Unit tests') {
                ansiColor('xterm') {
                    sh("${MAKE} unit-test")
                }
            }

            stage('Build image') {
                sh("${MAKE} build")
            }

            stage('API tests') {
                ansiColor('xterm') {
                    sh("${MAKE} api-test")
                }
            }

            stage('Validate test results') {
                junit "**/junit.xml"
                step([
                    $class: 'CoberturaPublisher',
                    autoUpdateHealth: false,
                    autoUpdateStability: false,
                    coberturaReportFile: 'coverage/coverage.xml',
                    failUnhealthy: true,
                    failUnstable: true,
                    maxNumberOfBuilds: 0,
                    onlyStable: false,
                    sourceEncoding: 'ASCII',
                    zoomCoverageChart: false,
                    lineCoverageTargets: '100.0, 90.0, 50.0',
                ])  
            }
        } finally {
            stage ('Clean test environment') {
                sh("${MAKE} down")
            }
        }

        try {
            configFileProvider([configFile(fileId: 'disable-release', variable: 'DISABLE_RELEASE')]) {
                echo 'Production releases are DISABLED.  To enable, delete the "disable-release" config file from the service\'s folder'
            }
        } catch (Exception e) {
            stage('Publish image') {
                def pubSteps = [:]
                for (int i = 0; i < global.PUBLISHERS.size(); i++) {
                    def registry = "${global.PUBLISHERS[i]}"
                    def stepName  = "publishing image to [${i}] ${registry}"
                    pubSteps[stepName] = {
                        sh("${MAKE} push REGISTRY=${registry}")
                    }
                }
                parallel pubSteps
            }

            stage('Acceptance tests') {
                sh("${MAKE} ci/version.yml")
                archiveArtifacts artifacts: 'ci/version.yml'

                try {
                    staging = build job: env.GLOBAL_ACCEPTANCE_JOB, parameters: [
                        text(name: 'UPSTREAM_JOB_NAME', value: env.JOB_NAME),
                        text(name: 'OVERRIDE_BUILD_ID', value:"{{Name}} PR#${ghprbPullId}"),
                    ]
                } finally {
                    step([
                        $class: 'CopyArtifact',
                        filter: 'test/e2e/reports/cucumber.html',
                        fingerprintArtifacts: true,
                        flatten: true,
                        optional: true,
                        projectName: staging.buildVariables.AcceptanceTestJobName,
                        selector: [$class: 'SpecificBuildSelector', buildNumber: staging.buildVariables.AcceptanceTestBuildNumber],
                        target: 'reports',
                    ])
                    publishHTML([
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'reports',
                        reportFiles: 'cucumber.html',
                        reportName: 'Acceptance Test Report',
                        reportTitles: ''
                    ])
                }
            }
        }
    }
}
