apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{Name}}
spec:
  template:
    spec:
      containers:
      - name: {{Name}}
        resources:
          requests:
            memory: 512M
            cpu: 800m
          limits:
            memory: 1000M
            cpu: 1500m
